<a href="https://colab.research.google.com/github/Zaine-eng/Python-pandas-numpay-matplotlib/blob/main/Estudo09_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Utilizando o pacote Numpy**

Podemos dizer que o numpy é um pacote criado para facilitar as operações matemáticas.

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

O que seria um array? Seria uma lista, sendo que esta lista é composta de elementos do mesmo tipo.

In [3]:
type(a)

numpy.ndarray

In [6]:
b = np.array([(2,3,5), (8, 7, 0), (4, 5, 6)])

print(b)

[[2 3 5]
 [8 7 0]
 [4 5 6]]


Criamos uma matriz 3x3. 


---



In [7]:
c = np.zeros((4,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
d = np.ones((4,3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


E como seria uma matriz identidade ? Para isso você usaria uma função eye do numpy

In [13]:
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Aplicações do numpy na variável b.

In [16]:
b.sum()


40

In [17]:
b.std()

2.3622546250521443

In [18]:
b.max()

8

In [19]:
b.min()

0



---

