<a href="https://colab.research.google.com/github/Zaine-eng/Python-machine-learning/blob/main/Estudo01_biblioteca_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Biblioteca Pandas** 😁

Podemos resumir como uma biblioteca que trabalha com dataframe.

In [1]:
import pandas as pd

Criando o próprio dateframe com o pandas 

In [2]:
alunos = {'Nome': ['Ricardo', 'Pedro', 'Roberto', 'Carlos', 'Bruno'], 
           'Nota': [ 4, 8, 5.5, 9, 7.5],
          'Aprovado': ['Não','Sim', 'Não', 'Sim', 'Sim']}

In [20]:
alunosdf = pd.DataFrame(alunos)

In [21]:
print(alunosdf)

      Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   8.0      Sim
2  Roberto   5.5      Não
3   Carlos   9.0      Sim
4    Bruno   7.5      Sim


Uso do comando Series

In [10]:
objeto1 = pd.Series([2, 6, 9, 10, 5])
print(objeto1)

0     2
1     6
2     9
3    10
4     5
dtype: int64


Usando um array no munpy: (unidimensional e bidimensional)

In [16]:
import numpy as np
array2 = np.array([(2, 6, 9, 10, 5), (2, 3, 4, 5,8 )])
array1 = np.array([2, 6, 9, 10, 5])
print(array1)
print(array2)

[ 2  6  9 10  5]
[[ 2  6  9 10  5]
 [ 2  3  4  5  8]]


Transformar um array em um vetor 

In [17]:
objeto2 = pd.Series(array1)
print(objeto2)

0     2
1     6
2     9
3    10
4     5
dtype: int64


O que poderia acontecer se fizemos isso no array2 que é bidimensional, será que iria funcionar ? 

In [18]:
objeto2 = pd.Series(array2)
print(objeto2)

ValueError: ignored

Veja que não pode ser feito em elementos bidimensionais.

O comando Series é unidimensional 

O Series é visto no pandas como um dataframe de uma coluna só - ajuda a lembrar.

Series - pandas 

Array - numpay



---

